CREATE DATABASE STUDENT_MANAGEMENT_SYSTEM


USE STUDENT_MANAGEMENT_SYSTEM

 CREATE TABLE STUDENTS(
 STUDENT_ID INT PRIMARY KEY,
 NAME VARCHAR(20),
 AGE INT,
 GENDER CHAR(1)
 )

 CREATE TABLE COURSES
 (
 COURSE_ID INT PRIMARY KEY,
 COURSE_NAME VARCHAR(100)
 )

 CREATE TABLE MARKS
 (
 MARKID INT PRIMARY KEY,
 STUDENT_ID INT,
 COURSE_ID INT,
 MARKS INT,
 FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
 FOREIGN KEY(COURSE_ID) REFERENCES COURSES(COURSE_ID)
 )


INSERT INTO STUDENTS VALUES
(1,'KARTHI',20,'M'),
(2,'NARESH',20,'M'),
(3,'AYSWARYA',20,'F'),
(4,'ABDUL',21,'M'),
(5,'RANI',20,'F'),
(6,'LAKSHMI',20,'F')

INSERT INTO COURSES VALUES
(101,'MATHEMATICS'),
(102,'PHYSICS')

INSERT INTO MARKS VALUES
(1,1,101,85),
(2,1,102,95),
(3,2,101,55),
(4,2,102,45),
(5,3,101,95),
(6,3,102,100),
(7,4,101,81),
(8,4,102,88),
(9,5,101,56),
(10,5,102,45),
(11,6,101,65),
(12,6,102,75)


--> VIEW ALL STUDENTS AND THEIR MARKS

SELECT S.NAME, C.COURSE_NAME, M.MARKS FROM MARKS M 
JOIN COURSES C ON C.COURSE_ID = M.COURSE_ID
JOIN STUDENTS S ON M.STUDENT_ID=S.STUDENT_ID


--> GET AVERAGE MARKS PER COURSE

SELECT M.COURSE_ID,C.COURSE_NAME,AVG(MARKS) AS AVERAGE_MARKS FROM MARKS M
JOIN COURSES C ON M.COURSE_ID=C.COURSE_ID
GROUP BY M.COURSE_ID,C.COURSE_NAME



 SELECT * FROM STUDENTS
 SELECT * FROM COURSES
 SELECT * FROM MARKS